export default {
  features: [
    {
      tcid: '1',
      name: '@search-page-platinum-user-validation',
      path: '/digitalexperience/drafts/automation/regression/search-page?georouting=off&martech=off',
      tags: '@da-dx-search-page @regression @circleCi',
      data: {
        partnerLevel: 'dxp-platinum:',
        searchKeyword: 'dxRegressionTest25',
        cardTitle: 'Asset preview Public PDF Regular',
        cardDate: 'Last modified: May 5, 2026',
        cardSize: 'Size: 2.6 kB',
        cardTags: ['px', 'explore', 'Session Type', 'data activation', 'content velocity', 'bacom'],
        cardButtonLink: 'https://partners.stage.adobe.com/digitalexperience/preview/qa-test/public/automation-regression-asset-preview/Asset-preview-Public-pdf-regular.pdf.html',
        silverAssetTitle: 'Silver only page for testing search Automation',
        trainingLink: 'https://learningmanager.adobe.com/',
      },
    },
    {
      tcid: '2',
      name: '@search-page-silver-user-validation',
      path: '/digitalexperience/drafts/automation/regression/search-page?georouting=off&martech=off',
      tags: '@da-dx-search-page @regression @circleCi',
      data: {
        partnerLevel: 'dxp-silver:',
        searchKeyword: 'dxRegressionTest25',
        assetTitle1: 'Asset preview Community JPG Regular Automation',
        assetTitle2: 'Asset preview Community JPG Regular Automation',
        assetTitle3: 'Asset preview Silver PPTX Regular Automation',
        assetTitle4: 'Asset preview Public ZIP Netstorage Automation',
        silverAsset: 'Silver only page for testing search Automation',
      },
    },
    {
      tcid: '3',
      name: '@asset-preview-public-non-logged-in-user-validation',
      path: '/digitalexperience/preview/qa-test/public/automation-regression-asset-preview/Asset-preview-Public-pdf-regular.pdf.html',
      tags: '@da-dx-search-page @regression @circleCi',
      data: {
        assetTitle: 'Asset detail: Asset preview Public PDF Regular  Automation  (PDF)',
        assetDate: 'Date: ',
        assetDateValue: '5/5/2026',
        assetSummary: 'Summary: ',
        assetType: 'Type: ',
        assetTypeValue: 'PDF',
        assetTags: 'Tags: ',
        assetTagsValue: ['Public', 'PX', 'Adobe Partners', 'Explore', 'Networking', 'Data Activation', 'Content Velocity', 'Bacom', 'Resource', 'PDF'],
        assetSize: 'Size: ',
        assetSizeValue: '2.6 KB',
        assetUrl: '/digitalexperience-assets/qatest/asset-preview/Asset%20preview%20Public%20PDF%20Regular.pdf',
      },
    },
    {
      tcid: '4',
      name: '@asset-preview-community-logged-in-user-validation',
      path: '/digitalexperience/preview/restricted/qatest/asset-preview/Asset-preview-Community-JPG-Regular.jpg.html',
      tags: '@da-dx-search-page @regression @circleCi',
      data: {
        partnerLevel: 'dxp-community:',
        assetTitle: 'Asset detail: Asset preview Community JPG Regular Automation  (Image)',
        assetDate: 'Date: ',
        assetDateValue: '5/5/2026',
        assetSummary: 'Summary: ',
        assetSummaryValue: 'Asset preview Community JPG Regular Description',
        assetType: 'Type: ',
        assetTypeValue: 'Image',
        assetTags: 'Tags: ',
        assetTagsValue: ['Community', 'Silver', 'Gold', 'Platinum', 'PX', 'Discover', 'Try This at Home', 'Analysis & Insights', 'Solutions+', 'Gravity', 'Resource', 'Image'],
        assetSize: 'Size: ',
        assetSizeValue: '2.6 MB',
        assetUrl: '/digitalexperience-assets/qatest/asset-preview/Asset%20preview%20Public%20PDF%20Regular.pdf',
        searchAllAssetsPath: '/digitalexperience/home/search/',
        goldAssetLink: '/digitalexperience/preview/netstorage-assets/restricted/as/asset-preview-goldmp4netstorage.mp4.html',
        asssetPreviewTitle: 'Asset detail: Asset preview Gold MP4 Netstorage Automation  (Video)',
      },
    },
    {
      tcid: '5',
      name: '@asset-preview-silver-user-validation',
      path: '/digitalexperience/preview/restricted/qatest/asset-preview/Asset-preview-Silver-PPTX-Regular.pptx.html',
      tags: '@da-dx-search-page @regression @circleCi',
      data: {
        partnerLevel: 'dxp-silver:',
        assetTitle: 'Asset detail: Asset preview Silver PPTX Regular Automation  (Powerpoint)',
        assetDateValue: '5/5/2026',
        assetTypeValue: 'Powerpoint',
        assetTagsValue: ['Silver', 'Gold', 'Platinum', 'PX', 'Use Re-invest', 'Creativity Workshop', 'Messaging', 'B2B Orchestration', 'Build Info', 'Resource', 'Powerpoint'],
        assetSizeValue: '61.7 MB',
      },
    },
    {
      tcid: '6',
      name: '@asset-preview-zip-platinum-user-validation',
      path: '/digitalexperience/preview/netstorage-assets/public/as/asset_preview_publiczipnetstorage.zip.html',
      tags: '@da-dx-search-page @regression @circleCi',
      data: {
        partnerLevel: 'dxp-platinum:',
        assetTitle: 'Asset detail: Asset preview Public ZIP Netstorage Automation  (ZIP)',
        assetDateValue: '1/12/2026',
        assetSummaryValue: 'Asset preview Public ZIP Netstorage Description',
        assetTypeValue: 'ZIP',
        assetTagsValue: ['Public', 'PX', 'Acceleration', 'Special Guest', 'Omnichannel Journeys', 'Cross-functional Collaboration', 'Events', 'Resource', 'ZIP'],
        assetSizeValue: '0.4 KB',
      },
    },
    {
      tcid: '7',
      name: '@asset-preview-mp4-public-asset-gold-user-validation',
      path: '/digitalexperience/preview/netstorage-assets/restricted/as/asset-preview-goldmp4netstorage.mp4.html',
      tags: '@da-dx-search-page @regression @circleCi',
      data: {
        partnerLevel: 'dxp-gold:',
        assetTitle: 'Asset detail: Asset preview Gold MP4 Netstorage Automation  (Video)',
        assetDateValue: '5/5/2026',
        assetSummaryValue: 'Here is a description of the asset',
        assetTypeValue: 'Video',
        assetTagsValue: ['Future Webinar', 'Try This at Home', 'Video', 'Solutions+', 'Experience Cloud', 'PX', 'Adobe Advertising Cloud', 'Gravity', 'Gold', 'Analysis & Insights', 'Discover', 'Document', 'Platinum', 'Resource', 'Video'],
        assetSizeValue: '17.5 MB',
      },
    },
    {
      tcid: '8',
      name: '@asset-preview-platinum-asset-with-gold-user-validation',
      path: '/digitalexperience/preview/netstorage-assets/restricted/as/asset_preview_platinumdocxnetstorage.docx.html',
      tags: '@da-dx-search-page @regression @circleCi',
      data: {
        partnerLevel: 'dxp-gold:',
        assetTitle: 'Asset detail: Asset preview Platinum DOCX Netstorage Automation  (Word)',
        assetDateValue: '1/12/2026',
        assetSummaryValue: 'Asset preview Platinum DOCX Netstorage Description',
        assetTypeValue: 'Word',
        assetTagsValue: ['Platinum', 'PX', 'Explore', 'Networking', 'Data Activation', 'Content Velocity', 'Marketo', 'Resource', 'Word'],
        assetSizeValue: '27.6 KB',
      },
    },
    {
      tcid: '9',
      name: '@search-page-training-validation',
      path: '/digitalexperience/drafts/automation/regression/search-page?georouting=off&martech=off',
      tags: '@da-dx-search-page @regression @circleCi',
      data: {
        partnerLevel: 'dxp-platinum:',
        trainingLink: 'https://learningmanager.adobe.com/',
      },
    },
    {
      tcid: '10',
      name: '@search-page-uncheck-filters-flow-validation',
      path: '/digitalexperience/drafts/automation/regression/search-page?georouting=off&martech=off',
      tags: '@da-dx-search-page @regression @circleCi',
      data: {
        partnerLevel: 'dxp-silver:',
        searchKeyword: 'dxRegressionTest25',
        assetTitle1: 'Asset preview Public PDF Regular Automation',
        assetTitle2: 'Asset preview Community JPG Regular Automation',
        assetTitle3: 'Asset preview Silver PPTX Regular Automation',
        assetTitle4: 'Asset preview Silver PPTX Regular Automation',
        silverAsset: 'Silver only page for testing search Automation',
      },
    },
    {
      tcid: '11',
      name: '@restricted-asset-preview-message-non-signed-in-user',
      path: '/digitalexperience-assets/netstorage-assets/restricted/as/asset_preview_platinumdocxnetstorage.docx  ',
      tags: '@restricted-asset @da-dx-search-page @regression @circleCi',
      data: {
        textBlock: 'Access to view or download this asset is restricted to registered partners. Login or register now.',
        link: [{ text: 'register now', url: 'https://partners.stage.adobe.com/digitalexperience/s/registration' }],
      },
    },
    {
      tcid: '12',
      name: '@restricted-asset-preview-message-community-level',
      path: '/digitalexperience-assets/netstorage-assets/restricted/as/asset_preview_platinumdocxnetstorage.docx  ',
      tags: '@restricted-asset @da-dx-search-page @regression @circleCi',
      data: {
        partnerLevel: 'dxp-community:',
        textBlock: 'Access to view this asset is restricted by your partnership level. Upgrade to Silver now.',
        link: [{ text: 'Upgrade to Silver now', url: 'https://pp-staging.adobe.com/silver-membership.html' }],
      },
    },
    {
      tcid: '13',
      name: '@restricted-asset-preview-message-gold-level',
      path: '/digitalexperience-assets/netstorage-assets/restricted/as/asset_preview_platinumdocxnetstorage.docx  ',
      tags: '@restricted-asset @da-dx-search-page @regression @circleCi',
      data: {
        partnerLevel: 'dxp-gold:',
        textBlock: 'Access to view this asset is restricted by your partnership level. Learn about options to uplevel now',
        link: [{ text: 'uplevel now', url: ' https://partners.stage.adobe.com/digitalexperience/articles/support/benefits-center#upleveling' }],
      },
    },
    {
      tcid: '14',
      name: '@asset-special-character-filters',
      path: '/digitalexperience/drafts/automation/regression/search-page?filters=yes&industries=caas:industry/automotive-and-mobility&content-type=caas:content-type/plans-and-pricing&journey-phase=caas:journey-phase/acquisition&topic=caas:topic/invoices ',
      tags: '@da-dx-search-page @regression @circleCi',
      data: {
        partnerLevel: 'dxp-platinum:',
        cardTitle: 'MAPP Asset with -and- tags',
      },
    },
    {
      tcid: '15',
      name: '@direct-asset-preview',
      path: '/digitalexperience/home',
      tags: '@da-dx-search-page @regression @circleCi',
      data: {
        partnerLevel: 'dxp-community:',
        newURL: 'https://partners.stage.adobe.com/digitalexperience-assets/netstorage-assets/restricted/au/Automation_Regression_Silver_Asset_Preview.pdf',
        errorText: '404 Not Found',
      },
    },
    {
      tcid: '16',
      name: '@direct-public-asset-preview',
      path: '/digitalexperience-assets/qa-test/public/automation-regression-asset-preview/Automation_Regression_Public_Asset_Preview.pdf',
      tags: '@da-dx-search-page @regression @circleCi',
    },
    {
      tcid: '17',
      name: '@direct-protected-asset-preview',
      path: '/digitalexperience-assets/netstorage-assets/restricted/au/Automation_Regression_Silver_Asset_Preview.pdf',
      tags: '@da-dx-search-page @regression @circleCi',
      data: {
        partnerLevel: 'dxp-silver:',
        previewURL: 'https://partners.stage.adobe.com/digitalexperience/preview/netstorage-assets/restricted/au/Automation_Regression_Silver_Asset_Preview.pdf.html',
      },
    },
    {
      tcid: '18',
      name: '@training-card-details',
      path: '/digitalexperience/drafts/automation/regression/search-page',
      tags: '@da-dx-search-page @regression @circleCi',
      data: {
        partnerLevel: 'dxp-platinum:',
        cardTitle: 'Adobe Experience Manager Foundations - DX Certification',
        cardDate: 'May 7, 2026',
        cardSummaryValue: 'Intro to Adobe Experience Manager (AEM): Learn key concepts, solutions, features, and use cases within the AEM ecosystem.',
        cardIcon: 'url("https://partners.stage.adobe.com/eds/img/icons/course.svg\")',
      },
    },
  ],
};
