const ASSET_REDIRECT_TARGET = {
  stage: '/digitalexperience/preview/restricted/1/program-guide.pdf.html',
  main: '/digitalexperience/preview/public/1/program-guide.pdf.html',
};

export default {
  FeatureName: 'DX Smoke Tests',
  features: [
    {
      tcid: '1',
      name: '@desc-partner-directory-validate-access',
      testId: '@MWPW-168683',
      path: '/join',
      tags: '@da-dx-smoke-test',
    },
    {
      tcid: '2',
      name: '@desc-partner-directory-validate-links',
      testId: '@MWPW-168683',
      tags: '@da-dx-smoke-test',
      data: {
        contactUsSPURL: '/digitalexperience/m/forms/case',
        findPartnerSPURL: '/s/directory/solution',
        learnMoreSPURL: '/digitalexperience/about',
        contactUsTPURL: '/digitalexperience/m/forms/case',
        findPartnerTPURL: '/s/directory/technology',
        learnMoreTPURL: '/digitalexperience/about',
        contactUsARURL: '/en/apc-helpdesk',
        findPartnerARURL: '/channel?lang=en',
        learnMoreARURL: '/channelpartners/',
        visitAdobeExchangeURL: 'exchange.adobe.com/',
      },
    },
    {
      tcid: '3',
      name: '@desc-partner-directory-join-validate-links',
      testId: '@MWPW-168683',
      path: '/join',
      tags: '@da-dx-smoke-test',
      data: {
        learnMoreSPURL: '/digitalexperience/about',
        joinNowSPURL: '/digitalexperience/s/registration/',
        learnMoreTPURL: '/digitalexperience/about',
        joinNowTPURL: '/digitalexperience/s/registration/',
        learnMoreARURL: '/na/channelpartners/program/',
        joinNowARURL: '/na/channelpartners/enrollment/',
      },
    },
    {
      tcid: '4',
      name: '@smoke-test-become-a-partner',
      path: '/digitalexperience/?georouting=off&martech=off',
      // tags: '@da-dx-smoke-test',
      data: { becomAPartnerUrl: '/digitalexperience/s/registration' },
    },
    {
      tcid: '5',
      name: '@smoke-test-find-a-partner-validation',
      path: '/digitalexperience/?georouting=off&martech=off',
      tags: '@da-dx-smoke-test',
      data: { findAPartnerUrl: '/s/directory/solution' },
    },
    {
      tcid: '6',
      name: '@smoke-test-analytics-card-collection-validation',
      path: '/digitalexperience/products/analytics?georouting=off&martech=off',
      tags: '@da-dx-smoke-test',
      data: { partnerLevel: 'dxp-platinum:' },
    },
    {
      tcid: '7',
      name: '@smoke-test-sale-center-home-button-validation',
      path: '/digitalexperience/?georouting=off&martech=off',
      tags: '@da-dx-smoke-test',
      data: {
        partnerLevel: 'dxp-gold:',
        expectedSaleCenterUrl: '/digitalexperience/m/salescenter/',
        homeUrl: '/digitalexperience/home/',
      },
    },
    {
      tcid: '8',
      name: '@smoke-test-non-member-user-loged-in-validation',
      path: '/digitalexperience/?georouting=off&martech=off',
      tags: '@da-dx-smoke-test',
      data: {
        partnerLevel: 'cpp-distributor-india:',
        contactNotFoundUrl: '/digitalexperience/error/contact-not-found#',
      },
    },
    {
      tcid: '9',
      name: '@smoke-test-search-page-validation',
      path: '/digitalexperience/home/search/?georouting=off&martech=off',
      tags: '@da-dx-smoke-test',
      data: {
        partnerLevel: 'dxp-silver:',
        searchKeyword: 'Adobe',
      },
    },
    {
      tcid: '10',
      name: '@smoke-test-feedback-mechanism-validation',
      path: '/digitalexperience/?georouting=off&martech=off',
      tags: '@da-dx-smoke-test',
      data: {
        feedbackTitle: 'Rate this page',
        feedbackTextArea: 'Automation Test Keywords',
      },
    },
    {
      tcid: '11',
      name: '@smoke-test-error-flow-abandoned-user-case',
      path: '/digitalexperience/',
      tags: '@da-dx-smoke-test',
      data: {
        partnerLevel: 'dxp-abandoned:',
        expectedToSeeInURL: '/digitalexperience/error/account-inactive',
      },
    },
    {
      tcid: '12',
      name: '@smoke-test-error-flow-terminated-user-case',
      path: '/digitalexperience/',
      tags: '@da-dx-smoke-test',
      data: {
        partnerLevel: 'dxp-terminated:',
        expectedToSeeInURL: '/digitalexperience/error/ineligible',
      },
    },
    {
      tcid: '13',
      name: '@smoke-test-error-flow-rejected-user-case',
      path: '/digitalexperience/',
      tags: '@da-dx-smoke-test',
      data: {
        partnerLevel: 'dxp-rejected:',
        expectedToSeeInURL: '/digitalexperience/error/decline',
      },
    },
    {
      tcid: '14',
      name: '@smoke-test-error-flow-404-user-case',
      path: '/digitalexperience/home-page',
      tags: '@da-dx-smoke-test',
      data: {
        partnerLevel: 'dxp-gold:',
        expectedToSeeInURL: '/digitalexperience/home-page',
      },
    },
    {
      tcid: '15',
      name: '@smoke-test-jarvis-chat-validation',
      path: '/digitalexperience/',
      // tags: '@da-dx-smoke-test',
    },
    {
      tcid: '16',
      name: '@smoke-test-feedback-mechanism-restricted-page-validation',
      path: '/digitalexperience/',
      tags: '@da-dx-smoke-test',
      data: {
        partnerLevel: 'dxp-platinum:',
        feedbackTitle: 'Rate this page',
        feedbackTextArea: 'Automation Test Keywords',
      },
    },
    {
      tcid: '17',
      name: '@smoke-test-feedback-mechanism-with-query-parameter-validation',
      path: '/digitalexperience/?feedback=true',
      tags: '@da-dx-smoke-test',
      data: {
        feedbackTitle: 'Rate this page',
        feedbackTextArea: 'Automation Test Keywords',
      },
    },
    {
      tcid: '18',
      name: '@smoke-test-footer-validation-public-and-protected-pages',
      path: '/digitalexperience/',
      tags: '@da-dx-smoke-test',
      data: {
        partnerLevel: 'dxp-platinum:',
        facebookLink: 'https://www.facebook.com/adobe',
        instagramLink: 'https://www.instagram.com/adobe/',
        linkedinLink: 'https://www.linkedin.com/company/adobe-partners/',
        twitterLink: 'https://twitter.com/AdobePartner',
      },
    },
    {
      tcid: '19',
      name: '@smoke-test-footer-validation-404-and-react-include-pages',
      path: '/digitalexperience/home-page',
      tags: '@da-dx-smoke-test',
      data: {
        partnerLevel: 'dxp-platinum:',
        facebookLink: 'https://www.facebook.com/adobe',
        instagramLink: 'https://www.instagram.com/adobe/',
        linkedinLink: 'https://www.linkedin.com/company/adobe-partners/',
        twitterLink: 'https://twitter.com/AdobePartner',
        reactIncludePage: '/digitalexperience/home/manage-user',
      },
    },
    {
      tcid: '20',
      name: '@smoke-test-signout-redirect',
      path: '/digitalexperience/',
      tags: '@da-dx-smoke-test',
      data: {
        partnerLevel: 'dxp-community:',
        homeUrl: '/digitalexperience/home/',
      },
    },
    {
      tcid: '21',
      name: '@smoke-test-public-asset-accessibility-non-signed-in-user',
      path: '/digitalexperience/preview/public/1/program-guide.pdf.html',
      tags: '@da-dx-smoke-test',
      data: { expectedURL: '/digitalexperience-assets/public/1/program-guide.pdf' },
    },
    {
      tcid: '22',
      name: '@smoke-test-public-asset-accessibility-signed-in-user',
      path: '/digitalexperience/preview/public/1/program-guide.pdf.html',
      tags: '@da-dx-smoke-test',
      data: {
        partnerLevel: 'dxp-gold:',
        expectedURL: '/digitalexperience-assets/public/1/program-guide.pdf',
      },
    },
    {
      tcid: '23',
      name: '@smoke-test-search-public-asset',
      path: '/digitalexperience/home/search/?georouting=off&martech=off',
      tags: '@da-dx-smoke-test',
      data: {
        partnerLevel: 'dxp-platinum:',
        searchKeyword: 'Adobe Digital Experience Partner Program Guide',
        previewURL: '/digitalexperience/preview/public/1/program-guide.pdf.html',
      },
    },
    {
      tcid: '24',
      name: '@smoke-test-regular-asset-visibility-platinum-user',
      path: '/digitalexperience/home/search/?georouting=off&martech=off',
      tags: '@da-dx-smoke-test',
      data: {
        partnerLevel: 'dxp-platinum:',
        searchKeyword: 'Webinar Presentation: LLM Optimizer and Sites Optimizer',
        title: 'Webinar Presentation: Adobe LLM Optimizer Partner Enablement',
        previewURL: '/digitalexperience/preview/restricted/we/1/webinar-presentation-llm-optimizer-partner-enablement.pdf.html',
        expectedURL: '/digitalexperience-assets/restricted/we/1/webinar-presentation-llm-optimizer-partner-enablement.pdf',
      },
    },
    {
      tcid: '25',
      name: '@smoke-test-non-signed-in-user-cannot-access-restricted-asset',
      path: '/digitalexperience-assets/restricted/we/1/webinar-presentation-llm-site-optimizer.pdf',
      tags: '@da-dx-smoke-test',
      data: {
        expectedURL: '/digitalexperience/preview/restricted/we/1/webinar-presentation-llm-site-optimizer.pdf.html',
        registedURL: '/digitalexperience/s/registration',
      },
    },
    {
      tcid: '26',
      name: '@smoke-test-netstorage-asset-visibility-platinum-user',
      path: '/digitalexperience/home/search/?georouting=off&martech=off',
      tags: '@da-dx-smoke-test',
      data: {
        partnerLevel: 'dxp-platinum:',
        searchKeyword: 'Webinar Recording: LLM Optimizer and Sites Optimizer',
        title: 'Webinar Recording: LLM Optimizer Technical Enablement',
        previewURL: '/digitalexperience/preview/netstorage-assets/restricted/we/webinar-recording-llm-site-optimizer.mp4.html',
        expectedURL: '/digitalexperience/preview/netstorage-assets/restricted/we/webinar-recording-llm-optimizer-technical-enablement.mp4.html',
      },
    },
    {
      tcid: '27',
      name: '@redirects-asset-redirect-stage-prod',
      path: '/digitalexperience/about',
      tags: '@da-dx-smoke-test',
      data: {
        assetRedirectCtaHref: '/digitalexperience/preview/restricted/1/program-guide.pdf.html',
        expectedLandingPath: ASSET_REDIRECT_TARGET,
      },
    },
  ],
};
