export default {
  FeatureName: 'DX Smoke Tests',
  features: [
    {
      tcid: '1',
      name: '@desc-partner-directory-validate-access',
      testId: '@MWPW-168683',
      path: '/join',
      tags: '@da-dx-smoke-test',
    },
    {
      tcid: '2',
      name: '@desc-partner-directory-validate-links',
      testId: '@MWPW-168683',
      tags: '@da-dx-smoke-test',
      data: {
        contactUsSPURL: '/solution-partners/contact.html',
        findPartnerSPURL: '/s/directory/solution',
        learnMoreSPURL: '/solution-partners/about.html',
        contactUsTPURL: '/technologyprogram/experiencecloud/support.html',
        findPartnerTPURL: '/s/directory/technology',
        learnMoreTPURL: '/technologyprogram/experiencecloud/about.html',
        contactUsARURL: '/en/apc-helpdesk',
        findPartnerARURL: '/PartnerSearch?lang=en',
        learnMoreARURL: '/na/channelpartners/program/',
        visitAdobeExchangeURL: 'exchange.adobe.com/',
      },
    },
    {
      tcid: '3',
      name: '@desc-partner-directory-join-validate-links',
      testId: '@MWPW-168683',
      path: '/join',
      tags: '@da-dx-smoke-test',
      data: {
        learnMoreSPURL: '/solution-partners/about.html',
        joinNowSPURL: '/solution-partners/registration.html',
        learnMoreTPURL: '/technologyprogram/experiencecloud/about.html',
        joinNowTPURL: '/technologyprogram/experiencecloud/registration.html',
        learnMoreARURL: '/na/channelpartners/program/',
        joinNowARURL: '/na/channelpartners/enrollment/',
      },
    },
  ],
};
