export default {
  FeatureName: 'Gnav Personalisation',
  features: [
    {
      tcid: '1',
      name: '@gnav-personalisation-non-logged-in-user-accsess',
      path: '/digitalexperience/drafts/automation/regression/personalization/page-with-gnav',
      tags: '@da-dx-personalisation @regression @anonymous @circleCi',
      data: {
        segmentText: '(NOT) Partner NOT member :',
      }
    },
    {
        tcid: '2',
        name: '@gnav-personalisation-logged-in-platinum-user-accsess',
        path: '/digitalexperience/drafts/automation/regression/personalization/page-with-gnav',
        tags: '@da-dx-personalisation @regression @anonymous',
        data: {
            segmentBussinessSolution: 'Partner primary business solution: users primaryBusiness is solution',
            segemntBussinessTechnology: '(NOT) Partner primary',
            segmentBillngAdmin: 'Partner salescenter admin:',
            segmentDesignationType: '(NOT) Designation learning :',
            segmentAdmin : 'Partner admin: partner whos',
            partnerData: {
                partnerPortal: 'DXP',
                accessType: '["Billing Admin","Sales Center Admin","Admin"]',
                complianceExpiryDate: '1829174400000',
                complianceStatus: 'Completed',
                createdDate: '1766151816000',
                designationType: '["Legal and Compliance"]',
                email: 'yugo-test+dx-stage-platinum@adobetest.com',
                latestAgreementAccepted: 'true',
                latestAgreementAcceptedVersion: 'Feb 6, 2026',
                primaryBusiness: '["Solution"]',
                primaryContact: 'true',
                primaryJobRole: 'Product Management',
                purchasedPartnerLevel: 'Platinum',
                salesCenterAccess: 'true',
                specialState: 'normal',
                status: 'MEMBER',
                partnerLevel: 'Platinum',
            },
            gnavSegmentLevel: 'Partner platinum',
            gnavSegmentAdmin: 'Partner billing admin',
            gnavSegmentDesignation: 'Designation legal',
        }
    },
    {
      tcid: '3',
      name: '@gnav-personalisation-logged-in-gold-user-accsess',
      path: '/digitalexperience/drafts/automation/regression/personalization/page-with-gnav',
      tags: '@da-dx-personalisation @regression @anonymous',
      data: {
          segmentBussinessSolution: 'Partner primary business solution: users primaryBusiness is solution',
          segemntBussinessTechnology: '(NOT) Partner primary',
          segmentBillngAdmin: 'Partner salescenter admin:',
          segmentDesignationType: '(NOT) Designation learning :',
          segmentAdmin : 'Partner admin: partner whos',
          partnerData: {
              partnerPortal: 'DXP',
              accessType: '["Sales Center Admin"]',
              complianceExpiryDate: '1829174400000',
              complianceStatus: 'Completed',
              createdDate: '1766151816000',
              designationType: '["Legal and Compliance"]',
              email: 'yugo-test+dx-stage-platinum@adobetest.com',
              latestAgreementAccepted: 'true',
              latestAgreementAcceptedVersion: 'Feb 6, 2026',
              primaryBusiness: '["Solution"]',
              primaryContact: 'true',
              primaryJobRole: 'Product Management',
              purchasedPartnerLevel: 'Platinum',
              salesCenterAccess: 'true',
              specialState: 'normal',
              status: 'MEMBER',
              partnerLevel: 'Platinum',
          },
          gnavSegmentLevel: 'Partner platinum',
          gnavSegmentAdmin: 'Partner billing admin',
          gnavSegmentDesignation: 'Designation legal',
      }
  },
  ],
};