export default {
  FeatureName: 'Gnav Personalisation',
  features: [
    {
      tcid: '1',
      name: '@gnav-personalisation-non-logged-in-user-accsess',
      path: '/digitalexperience/drafts/automation/regression/personalization/page-with-gnav',
      tags: '@da-dx-personalisation @regression @anonymous @circleCi',
      data: {
        segmentText: '(NOT) Partner NOT member :',
      }
    },
    {
      tcid: '2',
      name: '@gnav-personalisation-logged-in-platinum-user-accsess',
      path: '/digitalexperience/drafts/automation/regression/personalization/page-with-gnav',
      tags: '@da-dx-personalisation @regression @anonymous',
      data: {
          partnerLevelSegmentText: 'Partner platinum',
          segmentBussinessSolution: 'Partner primary business solution: users primaryBusiness is solution',
          segemntBussinessTechnology: '(NOT) Partner primary',
          segmentBillngAdmin: 'Partner salescenter admin:',
          segmentDesignationType: '(NOT) Designation learning :',
          segmentAdmin : 'Partner admin: partner whos',
          partnerData: {
              partnerPortal: 'DXP',
              accessType: '["Billing Admin","Sales Center Admin","Admin"]',
              complianceExpiryDate: '1829174400000',
              complianceStatus: 'Completed',
              createdDate: '1766151816000',
              designationType: '["Legal and Compliance"]',
              email: 'yugo-test+dx-stage-platinum@adobetest.com',
              latestAgreementAccepted: 'true',
              latestAgreementAcceptedVersion: 'Feb 6, 2026',
              primaryBusiness: '["Solution"]',
              primaryContact: 'true',
              primaryJobRole: 'Product Management',
              purchasedPartnerLevel: 'Platinum',
              salesCenterAccess: 'true',
              specialState: 'normal',
              status: 'MEMBER',
              partnerLevel: 'Platinum',
            },
          gnavSegmentLevel: 'Partner platinum',
          gnavSegmentAdmin: 'Partner billing admin',
          gnavSegmentDesignation: 'Designation legal',
        }
    },
    {
      tcid: '3',
      name: '@gnav-personalisation-logged-in-gold-user-accsess',
      path: '/digitalexperience/drafts/automation/regression/personalization/page-with-gnav',
      tags: '@da-dx-personalisation @regression @anonymous',
      data: {
          partnerLevelSegmentText: 'Partner gold',
          accsesTypeSegment: 'Partner salescenter admin:',
          designationTypeSegment: 'Designation learning : partner whos designationType is "Learning & Development',
          primaryBusinessSegment: '(NOT) Partner Not primary',
          partnerTypeSegment: 'NOT) Partner billing admin:',
          partnerData: {
              partnerPortal: 'DXP',
              accessType: '["Sales Center Admin"]',
              complianceExpiryDate: '1829174400000',
              createdDate: '1766151816000',
              designationType: '["Learning & Development"]',
              latestAgreementAccepted: 'true',
              latestAgreementAcceptedVersion: 'Feb 6, 2026',
              primaryBusiness: '["Technology"]',
              primaryContact: 'false',
              primaryJobRole: 'Product Engineering',
              purchasedPartnerLevel: 'Gold',
              salesCenterAccess: 'true',
              status: 'MEMBER',
              partnerLevel: 'Gold',
          },
          gnavSegmentLevel: 'Partner gold',
          gnavSegmentAdmin: '(NOT) Partner admin',
          gnavSegmentDesignation: '(NOT) Designation legal',
      }
    },
    {
      tcid: '4',
      name: '@gnav-personalisation-logged-in-silver-user-accsess',
      path: '/digitalexperience/drafts/automation/regression/personalization/page-with-gnav',
      tags: '@da-dx-personalisation @regression @anonymous',
      data: {
        partnerLevelSegmentText: 'Partner silver',
        primaryBusinessSegment: 'Partner primary business solution: users primaryBusiness is solution',
        primaryBusinessTechnologySegment: '(NOT) Partner primary',
        designationTypeSegment: '(NOT) Designation learning :',
        partnerData: {
          partnerPortal: 'DXP',
          accessType: '["Billing Admin"]',
          complianceExpiryDate: '1829174400000',
          createdDate: '1766151816000',
          designationType: '["Legal and Compliance"]',
          latestAgreementAccepted: 'true',
          latestAgreementAcceptedVersion: 'Feb 6, 2026',
          primaryBusiness: '["Solution"]',
          primaryContact: 'false',
          primaryJobRole: 'Marketing',
          purchasedPartnerLevel: 'Silver',
          salesCenterAccess: 'true',
          status: 'MEMBER',
          partnerLevel: 'Silver',
        },
        gnavSegmentLevel: 'Partner silver',
        gnavSegmentBillingAdmin: 'Partner billing admin',
        gnavSegmentDesignation: 'Designation legal',
        gnavSegmentSalesAccess: '(NOT) Partner salescenter',
        gnavSegmentAdmin: '(NOT) Partner admin',
      },
    },
    {
      tcid: '5',
      name: '@gnav-personalisation-logged-in-community-user-accsess',
      path: '/digitalexperience/drafts/automation/regression/personalization/page-with-gnav',
      tags: '@da-dx-personalisation @regression @anonymous',
      data: {
        partnerLevelSegmentText: 'Partner community',
        primaryBusinessSegment: '(NOT) Partner Not primary',
        accsesTypeBuillingSegment: '(NOT) Partner billing admin:',
        accsesTypeSegment: 'Partner admin: partner whos',
        designationTypeSegment: 'Designation learning : partner whos designationType is "Learning & Development',
        partnerData: {
          partnerPortal: 'DXP',
          accessType: '["Admin"]',
          isAdmin: 'true',
          complianceExpiryDate: '1829174400000',
          createdDate: '1766151816000',
          designationType: '["Learning & Development"]',
          latestAgreementAccepted: 'true',
          latestAgreementAcceptedVersion: 'Feb 6, 2026',
          primaryBusiness: '["Technology"]',
          primaryContact: 'true',
          primaryJobRole: 'Learning and Development',
          purchasedPartnerLevel: 'Community',
          salesCenterAccess: 'true',
          status: 'MEMBER',
          partnerLevel: 'Community',
        },
        gnavSegmentLevel: 'Partner community',
        gnavSegmentAdmin: '(NOT) Partner salescenter',
        designationTypeGnavSegment: '(NOT) Designation legal',
        partnerCaseGnavSegment: 'Partner primary business',
      },
    },
    {
      tcid: '6',
      name: '@gnav-personalisation-logged-in-locked-compliance-past-user-accsess',
      path: '/digitalexperience/drafts/automation/regression/personalization/page-with-gnav',
      tags: '@da-dx-personalisation @regression @anonymous',
      data: {
        partnerLevelSegmentText: 'Partner community',
        primaryBusinessSegment: '(NOT) Partner Not primary',
        accsesTypeBuillingSegment: '(NOT) Partner billing admin:',
        accsesTypeSegment: '(NOT) Partner billing admin:',
        designationTypeSegment: 'Designation learning : partner whos designationType is "Learning & Development',
        lockedCompliancePastSegment: 'Locked compliance past: users',
        partnerData: {
          partnerPortal: 'DXP',
          accessType: '[]',
          isAdmin: 'true',
          complianceStatus: 'Completed',
          complianceExpiryDate: '1829174400000',
          createdDate: '1766151816000',
          designationType: '["Learning & Development"]',
          latestAgreementAccepted: 'true',
          latestAgreementAcceptedVersion: 'Feb 6, 2026',
          primaryBusiness: '["Technology"]',
          primaryContact: 'true',
          primaryJobRole: 'Learning and Development',
          purchasedPartnerLevel: 'Silver',
          salesCenterAccess: 'true',
          specialState: 'locked-compliance-past',
          status: 'MEMBER',
          partnerLevel: 'Community',
        },
        gnavSegmentLevel: 'Partner community',
        gnavSegmentAdmin: '(NOT) Partner admin',
        gnavSegmentSalesAccess: '(NOT) Partner salescenter',
        designationTypeGnavSegment: '(NOT) Designation legal',
        partnerCaseGnavSegment: 'Partner primary business',
        partnerUserGnavSegment: 'Partner user',
        lockedAccessGnavSegment: 'Locked access',
      },
    },
    {
      tcid: '7',
      name: '@gnav-personalisation-logged-in-locked-compliance-past-admin-user-accsess',
      path: '/digitalexperience/drafts/automation/regression/personalization/page-with-gnav',
      tags: '@da-dx-personalisation @regression @anonymous',
      data: {
        partnerLevelSegmentText: 'Partner community',
        primaryBusinessSegment: '(NOT) Partner Not primary',
        accsesTypeSegment: 'Partner admin: partner whos',
        designationTypeSegment: '(NOT) Designation learning :',
        lockedCompliancePastSegment: 'Locked compliance past: users',
        lockedComplianceNotCompletedSegment: 'Locked compliance: users who',
        partnerData: {
          partnerPortal: 'DXP',
          accessType: '["Billing Admin","Admin"]',
          isAdmin: 'true',
          complianceStatus: 'Not Completed',
          complianceExpiryDate: '1829174400000',
          createdDate: '1766151816000',
          designationType: '["Legal and Compliance"]',
          latestAgreementAccepted: 'true',
          latestAgreementAcceptedVersion: 'Feb 6, 2026',
          primaryBusiness: '["Technology"]',
          primaryContact: 'true',
          primaryJobRole: 'Learning and Development',
          purchasedPartnerLevel: 'Gold',
          salesCenterAccess: 'true',
          specialState: 'locked-compliance-past',
          status: 'MEMBER',
          partnerLevel: 'Community',
        },
        gnavSegmentLevel: 'Partner community',
        gnavSegmentAdmin: 'Partner billing admin',
        gnavSegmentSalesAccess: '(NOT) Partner salescenter',
        designationTypeGnavSegment: 'Designation legal',
        partnerCaseGnavSegment: 'Partner primary business',
      },
    },
    {
      tcid: '8',
      name: '@gnav-personalisation-new-user-30-days-segment',
      path: '/digitalexperience/drafts/automation/regression/personalization/mocked-personalization',
      tags: '@da-dx-personalisation @regression @anonymous',
      data: {
          partnerSegmentText: 'Partner-new-user-segment:',
          partnerData: {
              partnerPortal: 'DXP',
              accessType: '["Billing Admin","Sales Center Admin","Admin"]',
              complianceExpiryDate: '1829174400000',
              complianceStatus: 'Completed',
              anyverseryDate: -25,
              designationType: '["Legal and Compliance"]',
              email: 'yugo-test+dx-stage-platinum@adobetest.com',
              isAdmin: 'true',
              latestAgreementAccepted: 'true',
              latestAgreementAcceptedVersion: 'Feb 6, 2026',
              primaryBusiness: '["Solution"]',
              primaryContact: 'true',
              primaryJobRole: 'Product Management',
              purchasedPartnerLevel: 'Platinum',
              salesCenterAccess: 'true',
              status: 'MEMBER',
              partnerLevel: 'Platinum',
            },
        }
    },
    {
      tcid: '9',
      name: '@gnav-personalisation-new-user-60-days-segment',
      path: '/digitalexperience/drafts/automation/regression/personalization/mocked-personalization',
      tags: '@da-dx-personalisation @regression @anonymous',
      data: {
          partnerSegmentText: 'Partner-returning-user-60d:',
          partnerData: {
              partnerPortal: 'DXP',
              accessType: '["Billing Admin","Sales Center Admin","Admin"]',
              complianceExpiryDate: '1829174400000',
              complianceStatus: 'Completed',
              anyverseryDate: -55,
              designationType: '["Legal and Compliance"]',
              email: 'yugo-test+dx-stage-platinum@adobetest.com',
              isAdmin: 'true',
              latestAgreementAccepted: 'true',
              latestAgreementAcceptedVersion: 'Feb 6, 2026',
              primaryBusiness: '["Solution"]',
              primaryContact: 'true',
              primaryJobRole: 'Product Management',
              purchasedPartnerLevel: 'Platinum',
              salesCenterAccess: 'true',
              status: 'MEMBER',
              partnerLevel: 'Platinum',
            },
        }
    },
    {
      tcid: '10',
      name: '@gnav-personalisation-new-user-90-days-segment',
      path: '/digitalexperience/drafts/automation/regression/personalization/mocked-personalization',
      tags: '@da-dx-personalisation @regression @anonymous',
      data: {
          partnerSegmentText: 'Partner-returning-user-90d:',
          partnerData: {
              partnerPortal: 'DXP',
              accessType: '["Billing Admin","Sales Center Admin","Admin"]',
              complianceExpiryDate: '1829174400000',
              complianceStatus: 'Completed',
              anyverseryDate: -85,
              designationType: '["Legal and Compliance"]',
              email: 'yugo-test+dx-stage-platinum@adobetest.com',
              isAdmin: 'true',
              latestAgreementAccepted: 'true',
              latestAgreementAcceptedVersion: 'Feb 6, 2026',
              primaryBusiness: '["Solution"]',
              primaryContact: 'true',
              primaryJobRole: 'Product Management',
              purchasedPartnerLevel: 'Platinum',
              salesCenterAccess: 'true',
              status: 'MEMBER',
              partnerLevel: 'Platinum',
            },
        }
    },
    {
      tcid: '11',
      name: '@gnav-icons-test-validation',
      path: '/digitalexperience/drafts/automation/regression/personalization/page-with-gnav',
      tags: '@da-dx-personalisation @regression @anonymous',
      data: {
        partnerData: {
          partnerPortal: 'DXP',
          accessType: '["Billing Admin","Sales Center Admin","Admin"]',
          complianceExpiryDate: '1829174400000',
          complianceStatus: 'Completed',
          createdDate: '1766151816000',
          designationType: '["Legal and Compliance"]',
          email: 'yugo-test+dx-stage-platinum@adobetest.com',
          latestAgreementAccepted: 'true',
          latestAgreementAcceptedVersion: 'Feb 6, 2026',
          primaryBusiness: '["Solution"]',
          primaryContact: 'true',
          primaryJobRole: 'Product Management',
          purchasedPartnerLevel: 'Platinum',
          salesCenterAccess: 'true',
          specialState: 'normal',
          status: 'MEMBER',
          partnerLevel: 'Platinum',
        },
        handshakeIconLink: '/digitalexperience/m/salescenter/',
        globeIconLink: '/s/directory/solution',
        searchIconLink: '/digitalexperience/home/search/',
        menageUserIconLink: '/digitalexperience/home/manage-user',
        homeIconLink: '/digitalexperience/home/',
      },
    },
  ],
};