const DAY_MS = 24 * 60 * 60 * 1000;
const newlyApprovedDate = Math.floor((Date.now() - 15 * DAY_MS) / 1000) * 1000;

const basePartnerData = {
  partnerPortal: 'DXP',
  accessType: ['Billing Admin', 'Sales Center Admin', 'Admin'],
  complianceStatus: 'Not Completed',
  createdDate: 1788782768000,
  designationType: ['Legal and Compliance', 'Learning & Development'],
  isAdmin: true,
  latestAgreementAccepted: true,
  latestAgreementAcceptedVersion: 'Feb 6, 2026',
  level: 'Silver',
  newlyApprovedDate,
  primaryBusiness: ['Solution'],
  primaryContact: true,
  primaryJobRole: 'Finance/Business Operations',
  purchasedPartnerLevel: 'Silver',
  region: 'north-america',
  salesCenterAccess: true,
  status: 'MEMBER',
  partnerLevel: 'Silver',
};

export default {
  FeatureName: 'Calendly Feature',
  features: [
    {
      tcid: '1',
      name: '@calendly-ui-validation',
      path: '/digitalexperience/drafts/automation/regression/calendly',
      tags: '@da-dx-calendly @regression @circleCi',
      data: {
        partnerLevel: 'dxp-calendly-spet:',
        firstName: 'DO NOT USE Calendly',
        lastName: 'September',
        email: 'yugo-test+dx-stage-calendly-sept@adobetest.com',
        companyName: 'DO NOT USE Calendly Company September',
      },
    },
    {
      tcid: '2',
      name: '@calendly-expty-account-state-calls-state-management',
      path: '/digitalexperience/drafts/automation/regression/calendly',
      tags: '@da-dx-calendly @regression @anonymous',
      data: {
        stateManagementUrl: 'https://io-partners-dx.stage.adobe.com/api/v1/web/dx-partners-runtime/dxp-state-management',
        partnerData: {
          partnerPortal: 'DXP',
          accessType: ['Billing Admin', 'Sales Center Admin', 'Admin'],
          complianceStatus: 'Not Completed',
          createdDate: 1788782768000,
          designationType: ['Legal and Compliance', 'Learning & Development'],
          email: 'yugo-test+dx-calendly-admin-1@adobetest.com',
          isAdmin: true,
          latestAgreementAccepted: true,
          latestAgreementAcceptedVersion: 'Feb 6, 2026',
          level: 'Silver',
          newlyApprovedDate,
          primaryBusiness: ['Solution'],
          primaryContact: true,
          primaryJobRole: 'Finance/Business Operations',
          purchasedPartnerLevel: 'Silver',
          region: 'north-america',
          salesCenterAccess: true,
          status: 'MEMBER',
          partnerLevel: 'Silver',
        },
        partner_account_state: { DXP: {} },
      },
    },
    {
      tcid: '3',
      name: '@calendly-existing-account-does-not-call-state-management',
      path: '/digitalexperience/drafts/automation/regression/calendly',
      tags: '@da-dx-calendly @regression @anonymous',
      data: {
        stateManagementUrl: 'https://io-partners-dx.stage.adobe.com/api/v1/web/dx-partners-runtime/dxp-state-management',
        partnerData: {
          partnerPortal: 'DXP',
          accessType: ['Billing Admin', 'Sales Center Admin', 'Admin'],
          complianceStatus: 'Not Completed',
          createdDate: 1788782768000,
          designationType: ['Legal and Compliance', 'Learning & Development'],
          email: 'yugo-test+dx-calendly-admin-1@adobetest.com',
          isAdmin: true,
          latestAgreementAccepted: true,
          latestAgreementAcceptedVersion: 'Feb 6, 2026',
          level: 'Silver',
          newlyApprovedDate,
          primaryBusiness: ['Solution'],
          primaryContact: true,
          primaryJobRole: 'Finance/Business Operations',
          purchasedPartnerLevel: 'Silver',
          region: 'north-america',
          salesCenterAccess: true,
          status: 'MEMBER',
          partnerLevel: 'Silver',
        },
        partner_account_state: { DXP: { calendly: 'test' } },
      },
    },
  ],
};
