export default {
  FeatureName: 'DX Banners',
  features: [
    {
      tcid: '1',
      name: '@banners-platinum-user-anyversery-date-in-next90-days',
      path: '/digitalexperience/drafts/automation/regression/public-page',
      tags: '@da-dx-banners @regression @anonymous @da-dx-main',
      data: {
        partnerData: {
          partnerPortal: 'DXP',
          accessType: '["Billing Admin","Sales Center Admin","Admin"]',
          complianceStatus: 'Completed',
          daysToComplianceExpiry: 65,
          designationType: '["Legal and Compliance"]',
          email: 'yugo-test+dx-stage-platinum@adobetest.com',
          isAdmin: 'true',
          latestAgreementAccepted: 'true',
          latestAgreementAcceptedVersion: 'Feb 6, 2026',
          primaryBusiness: '["Solution"]',
          primaryContact: 'true',
          primaryJobRole: 'Product Management',
          purchasedPartnerLevel: 'Platinum',
          salesCenterAccess: 'true',
          status: 'MEMBER',
          partnerLevel: 'Platinum',
        },
        completeComplianceButtonLink: '/digitalexperience/m/manageprofile/companyinfo/information?open=compliance',
      },
    },
    {
      tcid: '2',
      name: '@banners-global-banner-on-public-page',
      path: '/digitalexperience/drafts/automation/regression/banner/global-banner-test-page',
      tags: '@da-dx-banners @regression @anonymous @da-dx-main',
      data: {
        globalBannerText: 'Live chat is unavailable on September 14, 2026. Please submit your support request here.',
        globalBannerCtaLink: '/digitalexperience/m/forms/case',
      },
    },
    {
      tcid: '3',
      name: '@banners-global-banner-displayed-under-bctq-banner',
      path: '/digitalexperience/drafts/automation/regression/banner/global-banner-test-page',
      tags: '@da-dx-banners @regression @da-dx-main',
      data: {
        partnerData: {
          partnerPortal: 'DXP',
          accessType: '["Billing Admin","Sales Center Admin","Admin"]',
          complianceStatus: 'Completed',
          daysToComplianceExpiry: 65,
          designationType: '["Legal and Compliance"]',
          email: 'yugo-test+dx-stage-platinum@adobetest.com',
          isAdmin: 'true',
          latestAgreementAccepted: 'true',
          latestAgreementAcceptedVersion: 'Feb 6, 2026',
          primaryBusiness: '["Solution"]',
          primaryContact: 'true',
          primaryJobRole: 'Product Management',
          purchasedPartnerLevel: 'Platinum',
          salesCenterAccess: 'true',
          status: 'MEMBER',
          partnerLevel: 'Platinum',
        },
        globalBannerText: 'Live chat is unavailable on September 14, 2026. Please submit your support request here.',
      },
    },
  ],
};
