export default {
  features: [
    {
      tcid: '1',
      name: '@manage-profile-admin-user',
      path: '/digitalexperience/home/manage-user',
      tags: '@da-dx-manage-profile @regression @circleCi',
      data: {
        partnerLevel: 'dxp-community:',
        userName: 'DONOT USE Yugo DX Stage Community New',
        userEmail: 'yugo-test+dx-stage-community@adobetest.com',
        userPartnerLevel: 'Community',
        manageCompanyLink: 'https://partners.stage.adobe.com/digitalexperience/home/manage-company',
        cardTitles: {
          2: 'Company information',
          3: 'Company contacts',
          4: 'Company entitlements',
          5: 'Partner directory',
          7: 'Track partnership',
          9: 'Specializations',
          10: 'Credentials',
          11: 'Customer deployments',
          12: 'Company Recognition',
          13: 'Support cases',
          14: 'Explore more',
        },
      },
    },
    {
      tcid: '2',
      name: '@manage-profile-noadmin-user',
      path: '/digitalexperience/home/manage-user',
      tags: '@da-dx-manage-profile @regression @circleCi',
      data: {
        partnerLevel: 'dxp-noadmin:',
        userName: 'DONOT USE Yugo DX Stage No Admin',
        userEmail: 'yugo-test+dx-stage-noadmin@adobetest.com',
        userPartnerLevel: 'Silver',
        manageCompanyLink: 'https://partners.stage.adobe.com/digitalexperience/home/manage-company',
        cardTitles: {
          2: 'Company information',
          3: 'Company contacts',
          4: 'Company entitlements',
          5: 'Partner directory',
          14: 'Explore more',
        },
      },
    },
    {
      tcid: '3',
      name: '@manage-profile-biling-admin-user',
      path: '/digitalexperience/home/manage-user',
      tags: '@da-dx-manage-profile @regression @circleCi',
      data: {
        partnerLevel: 'dxp-silver:',
        userName: 'DONOT USE Yugo DX Stage Silver New',
        userEmail: 'yugo-test+dx-stage-silver@adobetest.com',
        userPartnerLevel: 'Silver',
        manageCompanyLink: 'https://partners.stage.adobe.com/digitalexperience/home/manage-company',
        cardTitles: {
          2: 'Company information',
          3: 'Company contacts',
          4: 'Company entitlements',
          5: 'Partner directory',
          6: 'Track partnership',
          14: 'Explore more',
        },
      },
    },
    {
      tcid: '4',
      name: '@manage-profile-biling-admin-admin-user',
      path: '/digitalexperience/home/manage-user',
      tags: '@da-dx-manage-profile @regression @circleCi',
      data: {
        partnerLevel: 'dxp-platinum:',
        userName: 'DONOT USE Yugo DX Stage Platinum New',
        userEmail: 'yugo-test+dx-stage-platinum@adobetest.com',
        userPartnerLevel: 'Platinum',
        manageCompanyLink: 'https://partners.stage.adobe.com/digitalexperience/home/manage-company',
        cardTitles: {
          2: 'Company information',
          3: 'Company contacts',
          4: 'Company entitlements',
          5: 'Partner directory',
          8: 'Track partnership',
          9: 'Specializations',
          10: 'Credentials',
          11: 'Customer deployments',
          12: 'Company Recognition',
          13: 'Support cases',
          14: 'Explore more',
        },
      },
    },
  ],
};
